import { Metadata } from 'next'
import './global.css'
import Link from 'next/link'

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export const metadata: Metadata = {
  title: {
    default: 'Aprendiendo NextJS',
    absolute: '',
    template: '%s - Aprendiendo NextJS'
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <p>Header App</p>
          <nav>
            <Link href='/'>Home - </Link>
            <Link href='/acerca'>Acerca - </Link>
            <Link href='/contacto'>Contacto - </Link>
            <Link href='/blog'>Blog - </Link>
            <Link href='/productos'>Productos - </Link>
            <Link href='/login'>Login - </Link>
            <Link href='/registro'>Registro - </Link>
            <Link href='/password'>Recuperar - Password - </Link>
            <Link href='/dashboard'>DASHBOARD</Link>
          </nav>
        </header>

        <main>
          {children}
        </main>

        <footer>
          Footer App
        </footer>
      </body>
    </html>
  )
}
